# Generated by Django 2.0.9 on 2018-11-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailto', models.CharField(max_length=200, verbose_name='수신인')),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('send_result', models.BooleanField(default=False, verbose_name='결과')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name_plural': 'EmailSend Log',
                'ordering': ['-created_time'],
                'verbose_name': 'EmailSend Log',
            },
        ),
    ]
