# Generated by Django 2.0.9 on 2018-11-07 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsendlog',
            old_name='emailto',
            new_name='receiver',
        ),
        migrations.AddField(
            model_name='emailsendlog',
            name='sender',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='발신인'),
            preserve_default=False,
        ),
    ]
