# Generated by Django 2.0.9 on 2018-10-31 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록시간')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='변경시간')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='제목')),
                ('body', models.TextField(verbose_name='내용')),
                ('pub_time', models.DateTimeField(blank=True, null=True, verbose_name='게시일')),
                ('status', models.CharField(choices=[('d', '대기'), ('p', '게시')], default='p', max_length=1, verbose_name='상태')),
                ('comment_status', models.CharField(choices=[('o', '열기'), ('c', '닫기')], default='o', max_length=1, verbose_name='댓글 상태')),
                ('type', models.CharField(choices=[('a', '일반형'), ('p', '단독/전체페이지')], default='a', max_length=1, verbose_name='타입')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
            ],
            options={
                'ordering': ['-pub_time'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Article_Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='이름')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록시간')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='변경시간')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Artciel_footer',
                'verbose_name': 'Artciel_footer',
            },
        ),
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(default='My Blog', max_length=200, verbose_name='사이트명')),
                ('site_description', models.TextField(default='Hello this is My Blog', max_length=1000, verbose_name='사이트 설명')),
                ('site_keywords', models.TextField(default='Blog', max_length=1000, verbose_name='사이트키워드')),
                ('article_sub_length', models.IntegerField(default=300, verbose_name='글길이 제한')),
                ('sidebar_article_count', models.IntegerField(default=10, verbose_name='사이드바 글 수')),
                ('sidebar_comment_count', models.IntegerField(default=5, verbose_name='사이드바 댓글수')),
                ('open_site_comment', models.BooleanField(default=True, verbose_name='사이트 댓글 설정')),
                ('show_google_adsense', models.BooleanField(default=False, verbose_name='구글광고설정')),
                ('google_adsense_codes', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='구글에드센스 코드')),
                ('show_analytics', models.BooleanField(default=True, verbose_name='아날리틱스 설정')),
                ('analyticscode', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Analytics Code')),
                ('resource_path', models.CharField(default='/var/www/resource/', max_length=300, verbose_name='리소스 파일')),
            ],
            options={
                'verbose_name_plural': 'Blog Settings',
                'verbose_name': 'Blog Settings',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록시간')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='변경시간')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='분류명')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=60)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='선분류 카테고리')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'category',
                'verbose_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록시간')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='변경시간')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Tag')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=60)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Tag',
                'verbose_name': 'Tag',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Article_Footer'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='글쓴이'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
