# Generated by Django 2.0.9 on 2018-10-31 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsettings',
            name='sidebar_comment_count',
        ),
    ]
