# Generated by Django 2.0.9 on 2018-10-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebar',
            options={'ordering': ['sequence'], 'verbose_name': 'Sidebar', 'verbose_name_plural': 'Sidebar'},
        ),
    ]
