# Generated by Django 2.0.9 on 2018-11-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogsettings_sidebar_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='panorama_horizontal', max_length=30, verbose_name='아이콘'),
        ),
    ]
