# Generated by Django 2.0.9 on 2018-10-22 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181022_1403'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogSetting',
            new_name='BlogSettings',
        ),
        migrations.AlterModelOptions(
            name='blogsettings',
            options={'verbose_name': 'Blog Settings', 'verbose_name_plural': 'Blog Settings'},
        ),
    ]
