# Generated by Django 2.0.9 on 2018-10-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181022_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='사용여부'),
        ),
    ]
